### ISSUE TITLE
Error: tutorial_1_create_dataset.sh - No such file or directory

### ISSUE THREAD

**Issue by ashkan25** [miykael/nipype-beginner-s-guide#14]
Running OS X Version 10.11.4 with BASH version: 3.2.57(1)-release

It seems like the for loop on line 17 has a different behaviour depending on the BASH version you use:

    for id in {01..10}

The output I get is:
> 0
> 1
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9
> 10

There seems to be no padding zeros for the values that are single digit. This results in the script not being able to find any of the subject folders.

Changing line 17 to the following seemed to have fixed the issue for me:

    for id in $(seq -w 1 10)

**Comment by ashkan25** [comment]
For tutorial 2 as well: [tutorial_2_recon_shell.sh](https://github.com/miykael/nipype-beginner-s-guide/blob/master/scripts/tutorial_2_recon_shell.sh#L8)

**Comment by miykael** [comment]
Thanks @ashkan25, I will change that. I didn't know that the `{01..10}` is bash specific.

**Comment by miykael** [comment]
Everything should now be updated to `for id in $(seq -w 1 10)`.
Thank you again for the feedback!

**Comment by ashkan25** [comment]
No worries, thank you for the scripts!
