### ISSUE TITLE
reconall error in script tutorial_2_recon_python.py

### ISSUE THREAD

**Issue by nakohli** [miykael/nipype-beginner-s-guide#3]
Hi,

I am trying to run this script  and am getting an error of reconall at line 41 since that is not defined anywhere in the script. Do I need to do something else to make the script work ?

Appreciate the effort put in creating these scripts.

**Comment by miykael** [comment]
Hi @nakohli,
Yes, there is a typo in the script that isn't on the homepage. The line 30 actually should start with "reconall" and not with "econall". If you change that (and add the line "import os") at the beginning of the script, than everything should run smoothly.
I've updated the homepage and the scripts.

Thanks for pointing this out. And thanks for the nice words. If you run in any other errors or have any more questions, feel free to ask or point out where stuff is missing.
